GOOSE_MODE: auto
GOOSE_CLI_MIN_PRIORITY: 0.0
GOOSE_DISABLE_KEYRING: 1
GOOSE_MODEL: claude-3.7-sonnet
GOOSE_PLANNER_MODEL: gpt-4.1
GOOSE_PROVIDER: github_copilot
extensions:
  computercontroller:
    bundled: true
    display_name: Computer Controller
    enabled: true
    name: computercontroller
    timeout: 300
    type: builtin
  ddg-search:
    args:
      - duckduckgo-mcp-server
    bundled: null
    cmd: uvx
    description: null
    enabled: true
    env_keys: []
    envs: {}
    name: ddg-search
    timeout: 300
    type: stdio
  developer:
    bundled: true
    display_name: Developer
    enabled: true
    name: developer
    timeout: 300
    type: builtin
  fetch:
    args:
      - mcp-server-fetch
    bundled: null
    cmd: uvx
    description: null
    enabled: true
    env_keys: []
    envs: {}
    name: fetch
    timeout: 300
    type: stdio
  memory:
    bundled: true
    display_name: Memory
    enabled: true
    name: memory
    timeout: 300
    type: builtin
  pdf:
    args:
      - mcp-read-pdf
    bundled: null
    cmd: uvx
    description: null
    enabled: true
    env_keys: []
    envs: {}
    name: pdf
    timeout: 300
    type: stdio
GOOSE_PLANNER_PROVIDER: github_copilot
