local opts = {
  ensure_installed = {
    "air",
    "black",
    "clang-format",
    "clangd",
    "cmake-language-server",
    "codelldb",
    "cpptools",
    "cucumber-language-server",
    "cuelsp",
    "debugpy",
    "delve",
    "docker-compose-language-service",
    "dockerfile-language-server",
    "emmet-ls",
    "go-debug-adapter",
    "gofumpt",
    "goimports",
    "goimports-reviser",
    "golangci-lint",
    "golangci-lint-langserver",
    "golines",
    "gomodifytags",
    "gopls",
    "gotests",
    "iferr",
    "impl",
    "lua-language-server",
    "markdownlint",
    "mesonlsp",
    "mypy",
    "prettier",
    "prettierd",
    "protolint",
    "pyright",
    "ruff",
    "svelte-language-server",
    "tailwindcss-language-server",
    "typescript-language-server",
  },
}

return {
  opts = opts,
}
